[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python bot-gemini.py --transport daily"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
